version: '3.8'
services:
  db:
    # https://hub.docker.com/_/mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    # https://hub.docker.com/_/wordpress
    image: wordpress:6.0.3-php8.1-apache
    ports:
      - "$WP_PORT:80"
    restart: always
    volumes:
      - wp_data:/var/www/html/
      - ./wp-content:/var/www/html/wp-content
      - ./shared:/var/www/html/shared
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1

  adminer:
    image: adminer
    restart: always
    ports:
      - "$ADMINER_PORT:8080"
    env_file: .env

  # cli:
  #   image: wordpress:cli-php8.1
  #   volumes:
  #     - wp_data:/var/www/html/
  #     - ./wp-content:/var/www/html/wp-content
  #     - ./shared:/var/www/html/shared
  #   depends_on:
  #     - db
  #     - wordpress
  #   command: "--info"
  #   user: xfs
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_NAME: wordpress
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress

volumes:
  wp_data:
  db_data:
